# Generated by Django 5.2.3 on 2025-06-16 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('sole', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('ltd', 'Limited Company'), ('cooperative', 'Cooperative Society'), ('ngo', 'Non-Governmental Organization'), ('other', 'Other')], max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(choices=[('001', 'Mombasa'), ('002', 'Kwale'), ('003', 'Kilifi'), ('004', 'Tana River'), ('005', 'Lamu'), ('006', 'Taita Taveta'), ('007', 'Garissa'), ('008', 'Wajir'), ('009', 'Mandera'), ('010', 'Marsabit'), ('011', 'Isiolo'), ('012', 'Meru'), ('013', 'Tharaka Nithi'), ('014', 'Embu'), ('015', 'Kitui'), ('016', 'Machakos'), ('017', 'Makueni'), ('018', 'Nyandarua'), ('019', 'Nyeri'), ('020', 'Kirinyaga'), ('021', "Murang'a"), ('022', 'Kiambu'), ('023', 'Turkana'), ('024', 'West Pokot'), ('025', 'Samburu'), ('026', 'Trans Nzoia'), ('027', 'Uasin Gishu'), ('028', 'Elgeyo Marakwet'), ('029', 'Nandi'), ('030', 'Baringo'), ('031', 'Laikipia'), ('032', 'Nakuru'), ('033', 'Narok'), ('034', 'Kajiado'), ('035', 'Kericho'), ('036', 'Bomet'), ('037', 'Kakamega'), ('038', 'Vihiga'), ('039', 'Bungoma'), ('040', 'Busia'), ('041', 'Siaya'), ('042', 'Kisumu'), ('043', 'Homa Bay'), ('044', 'Migori'), ('045', 'Kisii'), ('046', 'Nyamira'), ('047', 'Nairobi')], max_length=3)),
                ('physical_address', models.TextField()),
                ('date_established', models.DateField()),
                ('id_front', models.ImageField(upload_to='ids/front/')),
                ('id_back', models.ImageField(upload_to='ids/back/')),
                ('registration_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
