# Generated by Django 5.2.3 on 2025-07-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('sole', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('company', 'Limited Company'), ('cooperative', 'Cooperative Society'), ('ngo', 'Non-Governmental Organization'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', models.JSONField(help_text='List of directors')),
                ('shareholders', models.JSONField(help_text='List of shareholders with shares info')),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.JSONField(help_text='List of partners with names, IDs, PINs, contacts')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_detail', to='business.business')),
            ],
        ),
    ]
