# Generated by Django 5.2.3 on 2025-07-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
