# Generated by Django 5.2.3 on 2025-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_is_approved_business_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='shareholders',
        ),
        migrations.RemoveField(
            model_name='partnershipdetail',
            name='partners',
        ),
        migrations.AddField(
            model_name='partnershipdetail',
            name='partners_id_numbers',
            field=models.CharField(default=3, help_text='Comma-separated ID numbers of partners', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnershipdetail',
            name='partners_name',
            field=models.CharField(default=4, help_text='Comma-separated full names of partners', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='directors',
            field=models.CharField(help_text='Comma-separated full names of directors', max_length=512),
        ),
    ]
