# Generated by Django 5.2.3 on 2025-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_companydetail_directors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='ids/back/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='ids/front/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='physical_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
